services:
  - name: jitsi-web
    type: web
    env: docker
    dockerfilePath: ./web/Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: JITSI_IMAGE_VERSION
        value: stable-9909
      - key: HTTP_PORT
        value: "80"
      - key: HTTPS_PORT
        value: "443"
    ports:
      - name: http
        port: 80
      - name: https
        port: 443


  - name: jitsi-prosody
    type: worker
    env: docker
    dockerfilePath: ./prosody/Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: XMPP_PORT
        value: "5222"
      - key: PROSODY_S2S_PORT
        value: "5269"
      - key: PROSODY_HTTP_PORT
        value: "5280"


  - name: jitsi-jicofo
    type: worker
    env: docker
    dockerfilePath: ./jicofo/Dockerfile
    buildCommand: ""
    startCommand: ""


  - name: jitsi-jvb
    type: worker
    env: docker
    dockerfilePath: ./jvb/Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: JVB_PORT
        value: "10000"

